[package]
name = "korstick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.4"
trayicon = "0.2.0"
winapi = { version = "0.3.9", features = ["winuser"] }
winit = "0.30.3"
